version: "3.9"
services:
  postgres:
    container_name: "postgres"
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5439:5432"
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: habrdb
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: habrpguser
      DATABASE_PASSWORD: pgpwd4habr
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres
  stakewolle-back:
    build: .
    environment:
      DB_NAME: "habrdb"
      DB_USER: "habrpguser"
      DB_PASSWORD: "pgpwd4habr"
      DB_HOST: "postgres"
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - postgres
